### ISSUE TITLE
Loosen dependency version requirements

### ISSUE THREAD

**Issue by owenlamont** [RustyGuard/alembic-postgresql-enum#1]
Hi, just discovered your package and I love the idea, migrating Postgresql Enums has been a huge pain for us. I have a really hard time trying it in an existing Python environment since it pins its dependency versions so tightly though, are you able to loosen those version dependencies as much as practical?

Does it work with SQLAlchemy 1.4 or does it depend on SQLAlchemy 2+ features?

**Comment by RustyGuard** [comment]
@owenlamont there is no dependency on new features. I will test this library on some of my older projects to be sure that it actually works on 1.4

**Comment by RustyGuard** [comment]
Tested library on SqlAlchemy 1.4, Python 3.7 version. Seems to be working. Updated dependencies accordingly

**Comment by owenlamont** [comment]
Thank you very much!
