### ISSUE TITLE
Add automated regression tests

### ISSUE THREAD

**Issue by owenlamont** [RustyGuard/alembic-postgresql-enum#2]
I was wondering if you could add some automated regression tests into a GitHub pipeline using something like [pytest-postgresql](https://pypi.org/project/pytest-postgresql/) to automatically exercise each of the enum modifying features.

**Comment by owenlamont** [comment]
Thanks so much for addressing the dependency version issue I raised so fast - I know this is a longer-term larger request.

I'm preparing for a local PyCon for the next month or so but might be able to help with this issue afterwards if you think it has merit and haven't addressed it already.

**Comment by RustyGuard** [comment]
That is a good idea, I will try it out in new branch.
